import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Comprehensive MENA Food Database
// Nutritional values are per serving size specified

const menaFoods = [
  // ==================== EGYPTIAN MAIN DISHES ====================
  {
    externalId: 'eg-koshary',
    nameEn: 'Koshary',
    nameAr: 'كشري',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'traditional',
    servingSizeG: 350,
    servingUnit: 'plate',
    calories: 550,
    proteinG: 15,
    carbsG: 95,
    fatG: 12,
    fiberG: 8,
    tags: ['vegetarian', 'egyptian', 'high-carb', 'street-food'],
    availableAt: ['restaurants', 'street-vendors', 'home'],
  },
  {
    externalId: 'eg-ful-medames',
    nameEn: 'Ful Medames',
    nameAr: 'فول مدمس',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'breakfast',
    servingSizeG: 200,
    servingUnit: 'bowl',
    calories: 230,
    proteinG: 13,
    carbsG: 32,
    fatG: 6,
    fiberG: 9,
    tags: ['vegetarian', 'egyptian', 'high-protein', 'breakfast', 'high-fiber'],
    availableAt: ['restaurants', 'street-vendors', 'home'],
  },
  {
    externalId: 'eg-falafel-tameya',
    nameEn: 'Tameya (Egyptian Falafel)',
    nameAr: 'طعمية',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'breakfast',
    servingSizeG: 100,
    servingUnit: '4 pieces',
    calories: 330,
    proteinG: 13,
    carbsG: 31,
    fatG: 18,
    fiberG: 5,
    tags: ['vegetarian', 'egyptian', 'fried', 'breakfast'],
    availableAt: ['restaurants', 'street-vendors', 'home'],
  },
  {
    externalId: 'eg-molokhia',
    nameEn: 'Molokhia with Chicken',
    nameAr: 'ملوخية بالفراخ',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'traditional',
    servingSizeG: 300,
    servingUnit: 'bowl with rice',
    calories: 420,
    proteinG: 28,
    carbsG: 45,
    fatG: 14,
    fiberG: 4,
    tags: ['egyptian', 'high-protein', 'lunch', 'dinner'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-mahshi',
    nameEn: 'Mahshi (Stuffed Vegetables)',
    nameAr: 'محشي',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'traditional',
    servingSizeG: 250,
    servingUnit: 'serving',
    calories: 320,
    proteinG: 8,
    carbsG: 48,
    fatG: 12,
    fiberG: 6,
    tags: ['egyptian', 'vegetarian-option', 'lunch', 'dinner'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-kofta',
    nameEn: 'Kofta (Grilled)',
    nameAr: 'كفتة مشوية',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'grilled',
    servingSizeG: 150,
    servingUnit: '3 skewers',
    calories: 380,
    proteinG: 28,
    carbsG: 5,
    fatG: 28,
    fiberG: 1,
    tags: ['egyptian', 'high-protein', 'grilled', 'keto-friendly'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-kebab',
    nameEn: 'Kebab (Grilled Lamb)',
    nameAr: 'كباب',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'grilled',
    servingSizeG: 150,
    servingUnit: '3 skewers',
    calories: 350,
    proteinG: 30,
    carbsG: 2,
    fatG: 24,
    fiberG: 0,
    tags: ['egyptian', 'high-protein', 'grilled', 'keto-friendly'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-fattah',
    nameEn: 'Fattah',
    nameAr: 'فتة',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'traditional',
    servingSizeG: 400,
    servingUnit: 'plate',
    calories: 680,
    proteinG: 32,
    carbsG: 65,
    fatG: 32,
    fiberG: 3,
    tags: ['egyptian', 'high-calorie', 'eid', 'celebration'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-hawawshi',
    nameEn: 'Hawawshi',
    nameAr: 'حواوشي',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'street-food',
    servingSizeG: 200,
    servingUnit: '1 piece',
    calories: 520,
    proteinG: 22,
    carbsG: 42,
    fatG: 28,
    fiberG: 2,
    tags: ['egyptian', 'street-food', 'high-protein'],
    availableAt: ['restaurants', 'street-vendors'],
  },
  {
    externalId: 'eg-shawarma-chicken',
    nameEn: 'Chicken Shawarma Sandwich',
    nameAr: 'شاورما فراخ',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'sandwich',
    servingSizeG: 250,
    servingUnit: 'sandwich',
    calories: 480,
    proteinG: 28,
    carbsG: 45,
    fatG: 20,
    fiberG: 2,
    tags: ['egyptian', 'street-food', 'high-protein'],
    availableAt: ['restaurants', 'street-vendors'],
  },
  {
    externalId: 'eg-shawarma-meat',
    nameEn: 'Meat Shawarma Sandwich',
    nameAr: 'شاورما لحمة',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'sandwich',
    servingSizeG: 250,
    servingUnit: 'sandwich',
    calories: 550,
    proteinG: 26,
    carbsG: 45,
    fatG: 28,
    fiberG: 2,
    tags: ['egyptian', 'street-food', 'high-protein'],
    availableAt: ['restaurants', 'street-vendors'],
  },
  {
    externalId: 'eg-fiteer',
    nameEn: 'Fiteer Meshaltet (Plain)',
    nameAr: 'فطير مشلتت',
    isEgyptian: true,
    category: 'main_dish',
    subcategory: 'pastry',
    servingSizeG: 150,
    servingUnit: 'slice',
    calories: 450,
    proteinG: 8,
    carbsG: 52,
    fatG: 24,
    fiberG: 1,
    tags: ['egyptian', 'pastry', 'high-calorie'],
    availableAt: ['restaurants', 'bakeries'],
  },

  // ==================== RICE & GRAINS ====================
  {
    externalId: 'eg-rice-white',
    nameEn: 'Egyptian White Rice',
    nameAr: 'أرز أبيض',
    isEgyptian: true,
    category: 'grains',
    subcategory: 'rice',
    servingSizeG: 150,
    servingUnit: 'cup cooked',
    calories: 205,
    proteinG: 4,
    carbsG: 45,
    fatG: 0.5,
    fiberG: 0.6,
    tags: ['egyptian', 'staple', 'high-carb'],
    availableAt: ['home', 'restaurants'],
  },
  {
    externalId: 'eg-rice-with-vermicelli',
    nameEn: 'Rice with Vermicelli',
    nameAr: 'أرز بالشعرية',
    isEgyptian: true,
    category: 'grains',
    subcategory: 'rice',
    servingSizeG: 150,
    servingUnit: 'cup cooked',
    calories: 240,
    proteinG: 5,
    carbsG: 48,
    fatG: 3,
    fiberG: 1,
    tags: ['egyptian', 'staple', 'high-carb'],
    availableAt: ['home', 'restaurants'],
  },
  {
    externalId: 'eg-freek',
    nameEn: 'Freekeh',
    nameAr: 'فريك',
    isEgyptian: true,
    category: 'grains',
    subcategory: 'whole-grain',
    servingSizeG: 150,
    servingUnit: 'cup cooked',
    calories: 180,
    proteinG: 8,
    carbsG: 34,
    fatG: 2,
    fiberG: 6,
    tags: ['egyptian', 'whole-grain', 'high-fiber', 'high-protein'],
    availableAt: ['home', 'restaurants'],
  },

  // ==================== BREAD ====================
  {
    externalId: 'eg-aish-baladi',
    nameEn: 'Aish Baladi (Egyptian Bread)',
    nameAr: 'عيش بلدي',
    isEgyptian: true,
    category: 'bread',
    subcategory: 'flatbread',
    servingSizeG: 80,
    servingUnit: '1 loaf',
    calories: 165,
    proteinG: 6,
    carbsG: 33,
    fatG: 1,
    fiberG: 4,
    tags: ['egyptian', 'staple', 'whole-grain'],
    availableAt: ['bakeries', 'home'],
  },
  {
    externalId: 'eg-aish-shami',
    nameEn: 'Aish Shami (White Pita)',
    nameAr: 'عيش شامي',
    isEgyptian: true,
    category: 'bread',
    subcategory: 'flatbread',
    servingSizeG: 60,
    servingUnit: '1 piece',
    calories: 165,
    proteinG: 5,
    carbsG: 33,
    fatG: 1,
    fiberG: 1,
    tags: ['egyptian', 'staple'],
    availableAt: ['bakeries', 'home'],
  },

  // ==================== DAIRY ====================
  {
    externalId: 'eg-laban-rayeb',
    nameEn: 'Laban Rayeb (Buttermilk)',
    nameAr: 'لبن رايب',
    isEgyptian: true,
    category: 'dairy',
    subcategory: 'fermented',
    servingSizeG: 200,
    servingUnit: 'cup',
    calories: 100,
    proteinG: 8,
    carbsG: 12,
    fatG: 2,
    fiberG: 0,
    tags: ['egyptian', 'probiotic', 'high-protein'],
    availableAt: ['supermarkets', 'home'],
  },
  {
    externalId: 'eg-gibna-domyati',
    nameEn: 'Domyati Cheese',
    nameAr: 'جبنة دمياطي',
    isEgyptian: true,
    category: 'dairy',
    subcategory: 'cheese',
    servingSizeG: 50,
    servingUnit: 'slice',
    calories: 150,
    proteinG: 10,
    carbsG: 1,
    fatG: 12,
    fiberG: 0,
    tags: ['egyptian', 'high-protein', 'keto-friendly'],
    availableAt: ['supermarkets', 'home'],
  },
  {
    externalId: 'eg-gibna-areesh',
    nameEn: 'Areesh Cheese (Cottage)',
    nameAr: 'جبنة قريش',
    isEgyptian: true,
    category: 'dairy',
    subcategory: 'cheese',
    servingSizeG: 100,
    servingUnit: 'serving',
    calories: 80,
    proteinG: 14,
    carbsG: 3,
    fatG: 1,
    fiberG: 0,
    tags: ['egyptian', 'high-protein', 'low-fat', 'diet-friendly'],
    availableAt: ['supermarkets', 'home'],
  },

  // ==================== PROTEINS ====================
  {
    externalId: 'eg-grilled-chicken',
    nameEn: 'Grilled Chicken Breast',
    nameAr: 'صدر فراخ مشوي',
    isEgyptian: true,
    category: 'protein',
    subcategory: 'poultry',
    servingSizeG: 150,
    servingUnit: 'breast',
    calories: 230,
    proteinG: 43,
    carbsG: 0,
    fatG: 5,
    fiberG: 0,
    tags: ['high-protein', 'low-fat', 'grilled', 'diet-friendly'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-grilled-fish-bouri',
    nameEn: 'Grilled Bouri Fish',
    nameAr: 'سمك بوري مشوي',
    isEgyptian: true,
    category: 'protein',
    subcategory: 'seafood',
    servingSizeG: 200,
    servingUnit: 'fillet',
    calories: 220,
    proteinG: 40,
    carbsG: 0,
    fatG: 6,
    fiberG: 0,
    tags: ['high-protein', 'low-fat', 'grilled', 'omega-3'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-liver-alexandrian',
    nameEn: 'Alexandrian Liver',
    nameAr: 'كبدة اسكندراني',
    isEgyptian: true,
    category: 'protein',
    subcategory: 'organ-meat',
    servingSizeG: 150,
    servingUnit: 'serving',
    calories: 280,
    proteinG: 26,
    carbsG: 8,
    fatG: 15,
    fiberG: 1,
    tags: ['egyptian', 'high-protein', 'iron-rich', 'street-food'],
    availableAt: ['restaurants', 'street-vendors'],
  },
  {
    externalId: 'eg-eggs-scrambled',
    nameEn: 'Scrambled Eggs with Ghee',
    nameAr: 'بيض مقلي بالسمن',
    isEgyptian: true,
    category: 'protein',
    subcategory: 'eggs',
    servingSizeG: 120,
    servingUnit: '2 eggs',
    calories: 220,
    proteinG: 14,
    carbsG: 2,
    fatG: 18,
    fiberG: 0,
    tags: ['high-protein', 'breakfast', 'keto-friendly'],
    availableAt: ['home', 'restaurants'],
  },

  // ==================== VEGETABLES & SALADS ====================
  {
    externalId: 'eg-salata-baladi',
    nameEn: 'Egyptian Salad',
    nameAr: 'سلطة بلدي',
    isEgyptian: true,
    category: 'salad',
    subcategory: 'fresh',
    servingSizeG: 150,
    servingUnit: 'bowl',
    calories: 60,
    proteinG: 2,
    carbsG: 10,
    fatG: 2,
    fiberG: 3,
    tags: ['vegetarian', 'low-calorie', 'healthy'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-tahina-salad',
    nameEn: 'Tahini Salad',
    nameAr: 'سلطة طحينة',
    isEgyptian: true,
    category: 'salad',
    subcategory: 'dip',
    servingSizeG: 100,
    servingUnit: 'serving',
    calories: 180,
    proteinG: 5,
    carbsG: 8,
    fatG: 15,
    fiberG: 2,
    tags: ['vegetarian', 'healthy-fats', 'dip'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-baba-ghanoush',
    nameEn: 'Baba Ghanoush',
    nameAr: 'بابا غنوج',
    isEgyptian: true,
    category: 'salad',
    subcategory: 'dip',
    servingSizeG: 100,
    servingUnit: 'serving',
    calories: 120,
    proteinG: 3,
    carbsG: 10,
    fatG: 8,
    fiberG: 4,
    tags: ['vegetarian', 'healthy', 'dip'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-hummus',
    nameEn: 'Hummus',
    nameAr: 'حمص',
    isEgyptian: true,
    category: 'salad',
    subcategory: 'dip',
    servingSizeG: 100,
    servingUnit: 'serving',
    calories: 170,
    proteinG: 8,
    carbsG: 14,
    fatG: 10,
    fiberG: 6,
    tags: ['vegetarian', 'high-protein', 'high-fiber', 'dip'],
    availableAt: ['restaurants', 'home'],
  },

  // ==================== DESSERTS ====================
  {
    externalId: 'eg-basbousa',
    nameEn: 'Basbousa',
    nameAr: 'بسبوسة',
    isEgyptian: true,
    category: 'dessert',
    subcategory: 'traditional',
    servingSizeG: 80,
    servingUnit: 'piece',
    calories: 320,
    proteinG: 4,
    carbsG: 48,
    fatG: 13,
    fiberG: 1,
    tags: ['egyptian', 'sweet', 'high-calorie'],
    availableAt: ['bakeries', 'restaurants', 'home'],
  },
  {
    externalId: 'eg-konafa',
    nameEn: 'Konafa',
    nameAr: 'كنافة',
    isEgyptian: true,
    category: 'dessert',
    subcategory: 'traditional',
    servingSizeG: 120,
    servingUnit: 'slice',
    calories: 450,
    proteinG: 8,
    carbsG: 58,
    fatG: 22,
    fiberG: 1,
    tags: ['egyptian', 'sweet', 'high-calorie', 'ramadan'],
    availableAt: ['bakeries', 'restaurants'],
  },
  {
    externalId: 'eg-om-ali',
    nameEn: 'Om Ali',
    nameAr: 'أم علي',
    isEgyptian: true,
    category: 'dessert',
    subcategory: 'traditional',
    servingSizeG: 200,
    servingUnit: 'bowl',
    calories: 520,
    proteinG: 12,
    carbsG: 62,
    fatG: 26,
    fiberG: 2,
    tags: ['egyptian', 'sweet', 'high-calorie'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-qatayef',
    nameEn: 'Qatayef',
    nameAr: 'قطايف',
    isEgyptian: true,
    category: 'dessert',
    subcategory: 'traditional',
    servingSizeG: 60,
    servingUnit: '2 pieces',
    calories: 280,
    proteinG: 5,
    carbsG: 38,
    fatG: 12,
    fiberG: 1,
    tags: ['egyptian', 'sweet', 'ramadan'],
    availableAt: ['bakeries', 'restaurants'],
  },
  {
    externalId: 'eg-rice-pudding',
    nameEn: 'Roz Bel Laban (Rice Pudding)',
    nameAr: 'أرز باللبن',
    isEgyptian: true,
    category: 'dessert',
    subcategory: 'traditional',
    servingSizeG: 150,
    servingUnit: 'bowl',
    calories: 220,
    proteinG: 6,
    carbsG: 38,
    fatG: 5,
    fiberG: 0,
    tags: ['egyptian', 'sweet', 'comfort-food'],
    availableAt: ['restaurants', 'home'],
  },

  // ==================== BEVERAGES ====================
  {
    externalId: 'eg-karkade',
    nameEn: 'Karkade (Hibiscus Tea)',
    nameAr: 'كركديه',
    isEgyptian: true,
    category: 'beverage',
    subcategory: 'tea',
    servingSizeG: 250,
    servingUnit: 'cup',
    calories: 40,
    proteinG: 0,
    carbsG: 10,
    fatG: 0,
    fiberG: 0,
    tags: ['egyptian', 'traditional', 'low-calorie', 'ramadan'],
    availableAt: ['restaurants', 'home', 'cafes'],
  },
  {
    externalId: 'eg-sahlab',
    nameEn: 'Sahlab',
    nameAr: 'سحلب',
    isEgyptian: true,
    category: 'beverage',
    subcategory: 'hot-drink',
    servingSizeG: 250,
    servingUnit: 'cup',
    calories: 280,
    proteinG: 6,
    carbsG: 45,
    fatG: 8,
    fiberG: 1,
    tags: ['egyptian', 'winter', 'comfort-drink'],
    availableAt: ['restaurants', 'cafes', 'home'],
  },
  {
    externalId: 'eg-qamar-el-din',
    nameEn: 'Qamar El Din (Apricot Drink)',
    nameAr: 'قمر الدين',
    isEgyptian: true,
    category: 'beverage',
    subcategory: 'juice',
    servingSizeG: 250,
    servingUnit: 'cup',
    calories: 140,
    proteinG: 1,
    carbsG: 35,
    fatG: 0,
    fiberG: 2,
    tags: ['egyptian', 'ramadan', 'traditional'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-tamarind',
    nameEn: 'Tamarind Juice',
    nameAr: 'عصير تمر هندي',
    isEgyptian: true,
    category: 'beverage',
    subcategory: 'juice',
    servingSizeG: 250,
    servingUnit: 'cup',
    calories: 120,
    proteinG: 1,
    carbsG: 30,
    fatG: 0,
    fiberG: 1,
    tags: ['egyptian', 'ramadan', 'traditional'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-sugarcane-juice',
    nameEn: 'Sugarcane Juice',
    nameAr: 'عصير قصب',
    isEgyptian: true,
    category: 'beverage',
    subcategory: 'juice',
    servingSizeG: 300,
    servingUnit: 'cup',
    calories: 180,
    proteinG: 0,
    carbsG: 45,
    fatG: 0,
    fiberG: 0,
    tags: ['egyptian', 'street-food', 'natural-sugar'],
    availableAt: ['street-vendors'],
  },

  // ==================== RAMADAN SPECIALS ====================
  {
    externalId: 'eg-dates',
    nameEn: 'Dates (Balah)',
    nameAr: 'بلح',
    isEgyptian: true,
    category: 'fruit',
    subcategory: 'dried',
    servingSizeG: 40,
    servingUnit: '3 dates',
    calories: 110,
    proteinG: 1,
    carbsG: 29,
    fatG: 0,
    fiberG: 3,
    tags: ['ramadan', 'iftar', 'natural-sugar', 'high-fiber'],
    availableAt: ['supermarkets', 'home'],
  },
  {
    externalId: 'eg-shorbet-lisan-asfour',
    nameEn: 'Orzo Soup (Lisan Asfour)',
    nameAr: 'شوربة لسان عصفور',
    isEgyptian: true,
    category: 'soup',
    subcategory: 'traditional',
    servingSizeG: 250,
    servingUnit: 'bowl',
    calories: 150,
    proteinG: 8,
    carbsG: 22,
    fatG: 4,
    fiberG: 1,
    tags: ['egyptian', 'ramadan', 'comfort-food'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-sambousek-cheese',
    nameEn: 'Sambousek with Cheese',
    nameAr: 'سمبوسك بالجبنة',
    isEgyptian: true,
    category: 'appetizer',
    subcategory: 'fried',
    servingSizeG: 60,
    servingUnit: '3 pieces',
    calories: 240,
    proteinG: 6,
    carbsG: 24,
    fatG: 14,
    fiberG: 1,
    tags: ['egyptian', 'ramadan', 'fried', 'appetizer'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'eg-sambousek-meat',
    nameEn: 'Sambousek with Meat',
    nameAr: 'سمبوسك باللحمة',
    isEgyptian: true,
    category: 'appetizer',
    subcategory: 'fried',
    servingSizeG: 60,
    servingUnit: '3 pieces',
    calories: 260,
    proteinG: 10,
    carbsG: 22,
    fatG: 15,
    fiberG: 1,
    tags: ['egyptian', 'ramadan', 'fried', 'appetizer', 'high-protein'],
    availableAt: ['restaurants', 'home'],
  },

  // ==================== GULF/LEVANT FOODS ====================
  {
    externalId: 'gulf-kabsa',
    nameEn: 'Kabsa (Saudi Rice)',
    nameAr: 'كبسة',
    isEgyptian: false,
    category: 'main_dish',
    subcategory: 'rice-dish',
    servingSizeG: 400,
    servingUnit: 'plate',
    calories: 650,
    proteinG: 35,
    carbsG: 70,
    fatG: 25,
    fiberG: 3,
    tags: ['saudi', 'gulf', 'high-protein', 'rice'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'gulf-mandi',
    nameEn: 'Mandi',
    nameAr: 'مندي',
    isEgyptian: false,
    category: 'main_dish',
    subcategory: 'rice-dish',
    servingSizeG: 400,
    servingUnit: 'plate',
    calories: 620,
    proteinG: 38,
    carbsG: 65,
    fatG: 22,
    fiberG: 2,
    tags: ['yemeni', 'gulf', 'high-protein', 'rice'],
    availableAt: ['restaurants'],
  },
  {
    externalId: 'levant-mansaf',
    nameEn: 'Mansaf',
    nameAr: 'منسف',
    isEgyptian: false,
    category: 'main_dish',
    subcategory: 'rice-dish',
    servingSizeG: 450,
    servingUnit: 'plate',
    calories: 750,
    proteinG: 40,
    carbsG: 68,
    fatG: 35,
    fiberG: 2,
    tags: ['jordanian', 'levant', 'high-protein', 'celebration'],
    availableAt: ['restaurants'],
  },
  {
    externalId: 'levant-maklouba',
    nameEn: 'Maklouba',
    nameAr: 'مقلوبة',
    isEgyptian: false,
    category: 'main_dish',
    subcategory: 'rice-dish',
    servingSizeG: 350,
    servingUnit: 'serving',
    calories: 520,
    proteinG: 25,
    carbsG: 58,
    fatG: 20,
    fiberG: 4,
    tags: ['palestinian', 'levant', 'rice'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'levant-fattoush',
    nameEn: 'Fattoush Salad',
    nameAr: 'فتوش',
    isEgyptian: false,
    category: 'salad',
    subcategory: 'fresh',
    servingSizeG: 200,
    servingUnit: 'bowl',
    calories: 180,
    proteinG: 4,
    carbsG: 22,
    fatG: 10,
    fiberG: 4,
    tags: ['lebanese', 'levant', 'healthy', 'vegetarian'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'levant-tabbouleh',
    nameEn: 'Tabbouleh',
    nameAr: 'تبولة',
    isEgyptian: false,
    category: 'salad',
    subcategory: 'fresh',
    servingSizeG: 150,
    servingUnit: 'serving',
    calories: 120,
    proteinG: 3,
    carbsG: 16,
    fatG: 6,
    fiberG: 4,
    tags: ['lebanese', 'levant', 'healthy', 'vegetarian', 'high-fiber'],
    availableAt: ['restaurants', 'home'],
  },

  // ==================== HEALTHY/FITNESS OPTIONS ====================
  {
    externalId: 'fit-oats-with-fruit',
    nameEn: 'Oatmeal with Banana',
    nameAr: 'شوفان بالموز',
    isEgyptian: true,
    category: 'breakfast',
    subcategory: 'healthy',
    servingSizeG: 250,
    servingUnit: 'bowl',
    calories: 310,
    proteinG: 10,
    carbsG: 55,
    fatG: 6,
    fiberG: 8,
    tags: ['healthy', 'breakfast', 'high-fiber', 'pre-workout'],
    availableAt: ['home'],
  },
  {
    externalId: 'fit-greek-yogurt',
    nameEn: 'Greek Yogurt',
    nameAr: 'زبادي يوناني',
    isEgyptian: false,
    category: 'dairy',
    subcategory: 'yogurt',
    servingSizeG: 170,
    servingUnit: 'cup',
    calories: 100,
    proteinG: 17,
    carbsG: 6,
    fatG: 0.7,
    fiberG: 0,
    tags: ['high-protein', 'low-fat', 'healthy', 'post-workout'],
    availableAt: ['supermarkets'],
  },
  {
    externalId: 'fit-grilled-chicken-salad',
    nameEn: 'Grilled Chicken Salad',
    nameAr: 'سلطة فراخ مشوية',
    isEgyptian: true,
    category: 'salad',
    subcategory: 'protein',
    servingSizeG: 300,
    servingUnit: 'bowl',
    calories: 320,
    proteinG: 35,
    carbsG: 12,
    fatG: 15,
    fiberG: 4,
    tags: ['high-protein', 'healthy', 'diet-friendly', 'low-carb'],
    availableAt: ['restaurants', 'home'],
  },
  {
    externalId: 'fit-protein-shake',
    nameEn: 'Whey Protein Shake',
    nameAr: 'شيك بروتين',
    isEgyptian: false,
    category: 'supplement',
    subcategory: 'protein',
    servingSizeG: 350,
    servingUnit: 'shake',
    calories: 180,
    proteinG: 30,
    carbsG: 8,
    fatG: 3,
    fiberG: 1,
    tags: ['high-protein', 'post-workout', 'supplement'],
    availableAt: ['home', 'gyms'],
  },
  {
    externalId: 'fit-boiled-eggs',
    nameEn: 'Boiled Eggs',
    nameAr: 'بيض مسلوق',
    isEgyptian: true,
    category: 'protein',
    subcategory: 'eggs',
    servingSizeG: 100,
    servingUnit: '2 eggs',
    calories: 155,
    proteinG: 13,
    carbsG: 1,
    fatG: 11,
    fiberG: 0,
    tags: ['high-protein', 'healthy', 'snack', 'keto-friendly'],
    availableAt: ['home'],
  },
  {
    externalId: 'fit-avocado-toast',
    nameEn: 'Avocado Toast',
    nameAr: 'توست بالأفوكادو',
    isEgyptian: false,
    category: 'breakfast',
    subcategory: 'healthy',
    servingSizeG: 150,
    servingUnit: 'slice',
    calories: 280,
    proteinG: 7,
    carbsG: 28,
    fatG: 17,
    fiberG: 8,
    tags: ['healthy', 'breakfast', 'healthy-fats', 'high-fiber'],
    availableAt: ['cafes', 'home'],
  },
  {
    externalId: 'fit-mixed-nuts',
    nameEn: 'Mixed Nuts',
    nameAr: 'مكسرات مشكلة',
    isEgyptian: false,
    category: 'snack',
    subcategory: 'nuts',
    servingSizeG: 30,
    servingUnit: 'handful',
    calories: 185,
    proteinG: 5,
    carbsG: 6,
    fatG: 17,
    fiberG: 2,
    tags: ['healthy-fats', 'snack', 'high-protein', 'keto-friendly'],
    availableAt: ['supermarkets'],
  },
];

async function seedMenaFoods() {
  console.log('Starting MENA foods seed...');

  for (const food of menaFoods) {
    try {
      await prisma.food.upsert({
        where: { externalId: food.externalId },
        update: {
          nameEn: food.nameEn,
          nameAr: food.nameAr,
          isEgyptian: food.isEgyptian,
          category: food.category,
          subcategory: food.subcategory,
          servingSizeG: food.servingSizeG,
          servingUnit: food.servingUnit,
          calories: food.calories,
          proteinG: food.proteinG,
          carbsG: food.carbsG,
          fatG: food.fatG,
          fiberG: food.fiberG,
          tags: food.tags,
          availableAt: food.availableAt,
        },
        create: {
          externalId: food.externalId,
          nameEn: food.nameEn,
          nameAr: food.nameAr,
          isEgyptian: food.isEgyptian,
          category: food.category,
          subcategory: food.subcategory,
          servingSizeG: food.servingSizeG,
          servingUnit: food.servingUnit,
          calories: food.calories,
          proteinG: food.proteinG,
          carbsG: food.carbsG,
          fatG: food.fatG,
          fiberG: food.fiberG,
          tags: food.tags,
          availableAt: food.availableAt,
        },
      });
      console.log(`✓ ${food.nameEn} (${food.nameAr})`);
    } catch (error) {
      console.error(`✗ Failed to seed ${food.nameEn}:`, error);
    }
  }

  const count = await prisma.food.count({ where: { isEgyptian: true } });
  console.log(`\nSeeded ${count} Egyptian/MENA foods successfully!`);
}

seedMenaFoods()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
